### ISSUE TITLE
iPhoneの言語が英語のとき、今ココスタンプの受信ができない

### ISSUE THREAD

**Issue by tklisb** [lisb/hubot#1]
今ココスタンプのイベントが発生しない。

---

#### 参考

今ココスタンプをテキストで受信したときの一部抜粋。

```javascript
  robot.hear(/(.*)/, res => {
    console.log(res);
  });
```

##### 日本語
```
text: 'Hubot 今ココ：\n〒101-0021 東京都‎ 千代田区 外神田6丁目5番4号 (近辺)\nhttps://goo.gl/bDnurz',
```

##### 英語
```
text: 'Hubot I\'m here：\nTokyo‎ Chiyoda Sotokanda 452 Japan (Near)\nhttps://goo.gl/raXm1C',
```

**Comment by ghost** [comment]
botに影響があったのですね。すみません。
11月のリリースで、見やすい形式(Android版に近い形式)に変更していました。

ちなみに英語の方はGPSの精度か何かが足りていなくて情報が少ないように見えます。
何度か試していただくとよいかもしれません。
(iOSに住所を取得させていますが、精度がよくない場合など郵便番号がとれない場合があります)
